spring:
  cloud:
    gateway:
      discovery:
        locator:
          lowerCaseServiceId: true
          enabled: true
    consul:
      host: localhost
      port: 8501
      discovery:
        instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${spring.application.instance_id:${server.port}}
        service-name: spring-cloud-consumer
  application:
    name: spring-cloud-consumer
  mvc:
    view:
      suffix: .jsp
      prefix: /webapp/views/
  thymeleaf:
    cache: false
  zipkin:
    base-url: http://localhost:9411
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1 #抽样百分比,默认0.1 就是百分十
server:
  #设置Tomcat端口，默认8080
  port: 9000
  tomcat:
    #设置Tomcat编码
    uri-encoding: UTF-8
  context:
    #设置项目ContextPath
    path: /web
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000
management:
  endpoints:
    web:
      exposure:
        include: '*'
        exclude:
ribbon:
  ConnectTimeout: 60000
  MaxAutoRetries: 2
  MaxAutoRetriesNextServer: 1
  ReadTimeout: 60000
feign:
  hystrix:
    enabled: true
info:
  app.name: spring-cloud-consumer
  app.update: 2018-10-07
  build.groupId: $project.groupId$
  build.artifactId: $project.artifactId$
  build.version: $project.version$